---

local_r_cran_packages:
  - biocmanager
  - ggplot2
  - markdown
  - pheatmap
  - remotes
  - statmod

local_r_bioconductor_packages:
  - annotationhub
  - apeglm
  - clusterprofiler
  - deseq2
  - edger
  - ggtree
  - org.hs.eg.db
  - org.mm.eg.db
  - reactomepa

local_rstudio_server_version: "2026.09.0-174"
local_rstudio_server_package: "https://download2.rstudio.org/server/jammy/amd64/rstudio-server-{{ local_rstudio_server_version }}-amd64.deb"
